'use strict';
/* Expanded original instructional content. Diagrams are generated as SVG, not sourced from books. */
const DEEP={
'1.1':{name:'Structural Mechanics & Behavior',sections:[
['Load Path และ Free-Body Diagram','แรงภายนอกต้องมีเส้นทางถ่ายแรงผ่านสมาชิก จุดต่อ และฐานรองรับอย่างต่อเนื่อง การตัดแยกวัตถุเพื่อเขียน Free-Body Diagram (FBD) ต้องแทนแรงจากส่วนที่ถูกตัดออกด้วยแรงและโมเมนต์ที่กระทำต่อส่วนที่พิจารณา','สมการสมดุลของระบบระนาบคือ ΣFₓ = 0, ΣFᵧ = 0 และ ΣM = 0 สมการเหล่านี้เป็นเงื่อนไขจำเป็นของโครงสร้างที่อยู่ในสมดุลสถิต แต่ไม่เพียงพอที่จะคำนวณแรงทุกตัวในระบบ statically indeterminate','ลองวาด FBD ของคานยาว 6 m รับแรงกด 12 kN ที่กึ่งกลาง เมื่อรองรับแบบ pin และ roller จะได้แรงปฏิกิริยาแนวดิ่งข้างละ 6 kN จากสมมาตรและสมดุล','beam'],
['Compatibility และ Deformation','Compatibility คือเงื่อนไขว่าการเคลื่อนที่ของสมาชิกที่เชื่อมต่อกันต้องสัมพันธ์กันตามข้อจำกัดของจุดต่อ เช่น แผ่นแข็งที่เคลื่อนที่โดยไม่หมุนทำให้สปริงขนานที่ต่อกับแผ่นเดียวกันมีการยืดเท่ากัน','สำหรับสปริงเชิงเส้นสองตัวที่ต่อขนาน δ₁ = δ₂ = δ และ P = (k₁ + k₂)δ จึงได้ δ = P/(k₁+k₂) แรงในแต่ละสปริงคือ Pᵢ = kᵢδ','กำหนด P = 160 kN, k₁ = 300 kN/mm และ k₂ = 100 kN/mm จะได้ δ = 0.4 mm, P₁ = 120 kN และ P₂ = 40 kN ตรวจสอบ P₁+P₂ = 160 kN','spring'],
['Constitutive Relation และ Stiffness','Constitutive relation เชื่อมความเค้นกับความเครียด สำหรับแท่งรับแรงตามแนวแกนภายใต้สมมติฐานวัสดุยืดหยุ่นเชิงเส้นและหน้าตัดคงที่ ใช้ σ = Eε','เมื่อ σ = P/A และ ε = δ/L จะได้ P/A = Eδ/L จัดรูปเป็น P = (EA/L)δ จึงนิยาม axial stiffness k = EA/L หน่วยเป็นแรงต่อระยะ','แท่งเหล็ก E = 200000 N/mm², A = 1000 mm² และ L = 2000 mm มี k = 100000 N/mm หากรับ P = 100 kN จะยืด δ = 1 mm','bar'],
['Stability และ Rigid-Body Motion','ระบบอาจอยู่ในสมดุลแต่ไม่เสถียร หากข้อจำกัดการเคลื่อนที่ไม่เพียงพอ เช่น โครงสร้างที่สามารถเลื่อนหรือหมุนทั้งระบบได้โดยสมาชิกไม่เสียรูป','เมื่อประกอบ K u = F แล้ว หากยังมี rigid-body mode ที่ไม่ถูกจำกัด เมทริกซ์ K ที่ใช้แก้ระบบอาจเป็น singular ไม่สามารถหาการเคลื่อนที่ที่มีค่าเดียวได้','ตรวจ support restraints, connectivity, element releases และ degree of freedom ก่อนสรุปว่าเมทริกซ์เอกฐานเกิดจากสาเหตุใด','support']
]},
'1.2':{name:'Energy Methods',sections:[
['พลังงานความเครียด (Strain Energy)','พลังงานความเครียดคือพลังงานที่สะสมภายในวัตถุเมื่อเกิดการเสียรูปภายใต้แรง สำหรับระบบยืดหยุ่นเชิงเส้นและโหลดที่เพิ่มอย่างช้า ๆ พลังงานที่สะสมเท่ากับพื้นที่ใต้กราฟแรง–การเคลื่อนที่','สปริงเชิงเส้น P = kδ มี U = ∫₀^δ P(ξ)dξ = ½kδ² = P²/(2k) สำหรับแท่งรับแรงตามแนวแกนที่มี P, E, A คงที่ จะได้ U = P²L/(2EA)','สปริง k = 200 kN/mm รับแรง 40 kN มี δ = 0.2 mm และ U = ½(40 kN)(0.2 mm) = 4 kN·mm = 4 J','spring'],
['Virtual Work','หลักงานเสมือนใช้สมดุลระหว่างงานเสมือนภายนอกและภายใน ภายใต้ virtual displacement ที่เข้ากันได้กับเงื่อนไขรองรับ วิธีนี้ช่วยหาการเคลื่อนที่ในระบบที่แรงภายในทราบจากการวิเคราะห์','สำหรับโครงถักเชิงเส้น การเคลื่อนที่ตามทิศของ unit load เขียนได้เป็น Δ = Σ(Nᵢ nᵢ Lᵢ / AᵢEᵢ) โดย Nᵢ คือแรงจากโหลดจริง และ nᵢ คือแรงจาก unit load','ตัวอย่างแท่งเดียว L = 2 m, EA = 200 MN และแรงจริง 20 kN เมื่อใช้ unit load ในทิศเดียวกันจะได้ Δ = PL/(EA) = 0.2 mm','bar'],
['Castigliano’s Theorem','สำหรับโครงสร้างยืดหยุ่นเชิงเส้นที่มีพลังงานความเครียด U เป็นฟังก์ชันของแรงทั่วไป อนุพันธ์ของ U เทียบกับแรงจะให้การเคลื่อนที่ตามทิศของแรงนั้น','δᵢ = ∂U/∂Pᵢ และ θᵢ = ∂U/∂Mᵢ เมื่อใช้แรงและโมเมนต์ที่เป็นอิสระตามสมมติฐานของทฤษฎี','ถ้า U = P²L/(2EA) จะได้ ∂U/∂P = PL/(EA) ซึ่งตรงกับการยืดของแท่งจาก constitutive relation','bar'],
['การตรวจสอบ Energy Balance','พลังงานเป็นเครื่องมืออิสระสำหรับตรวจผลลัพธ์เชิงตัวเลข โดยเฉพาะระบบเชิงเส้นที่มี K สมมาตรและเป็นไปตามเงื่อนไขรองรับ','สำหรับระบบเชิงเส้น U = ½uᵀKu และเมื่อ Ku = F จะได้ U = ½uᵀF สำหรับการเพิ่มโหลดจากศูนย์แบบเป็นสัดส่วน','หาก F = 10 kN และ u = 2 mm สำหรับระบบหนึ่งองศาอิสระ จะได้ U = 10 kN·mm = 10 J ตรวจสอบว่าแรงและระยะใช้หน่วยสอดคล้องกัน','spring']
]},
'1.3':{name:'Linear Algebra for Structural Engineering',sections:[
['เวกเตอร์แรงและการเคลื่อนที่','เวกเตอร์บรรจุตัวแปรที่จัดลำดับตาม Degree of Freedom (DOF) เช่น ระบบสปริงสองจุดอาจใช้ u = [u₁,u₂]ᵀ และ F = [F₁,F₂]ᵀ ลำดับต้องตรงกันทุกเมทริกซ์','ระบบสมดุลเขียนเป็น Ku = F โดย K คือ global stiffness matrix ซึ่งมีขนาด n×n เมื่อมี n DOF ที่ใช้ในสมการ','ตัวอย่าง K = [[3,−1],[−1,2]] kN/mm และ u = [1,2] mm จะได้ F = [1,3] kN','matrix'],
['การประกอบ Stiffness Matrix','สมาชิกสปริงที่เชื่อมจุด i และ j มี element stiffness kₑ = k[[1,−1],[−1,1]] ซึ่งได้จากแรงภายในที่ขึ้นกับการยืดสัมพัทธ์ uⱼ−uᵢ','เมื่อนำสมาชิกหลายตัวมาประกอบ ค่าสัมประสิทธิ์ของ DOF ที่ซ้ำกันต้องบวก contribution จากสมาชิกทุกตัว และควรรักษาสมมาตรของ K สำหรับระบบยืดหยุ่นเชิงเส้นทั่วไป','สปริง k₁ ต่อจากพื้นถึงจุด 1 และ k₂ ต่อระหว่างจุด 1–2 ให้ K = [[k₁+k₂,−k₂],[−k₂,k₂]]','matrix'],
['Boundary Conditions และ Singular Matrix','ก่อนแก้ Ku = F ต้องแยก DOF ที่ถูกจำกัดออกจาก DOF ที่เป็นอิสระ หากไม่มี restraint เพียงพอ ระบบอาจมี rigid-body mode ที่ไม่ใช้พลังงานในการเคลื่อนที่','Partition เป็น Kff uf = Ff − Kfr ur สำหรับ prescribed displacement ur จากนั้นหา reaction ที่ restrained DOF ด้วยสมการเต็ม','เมทริกซ์ [[1,−1],[−1,1]] มี determinant = 0 เพราะเวกเตอร์ [1,1]ᵀ เป็น rigid translation ที่ไม่ทำให้สปริงยืด','matrix'],
['การตรวจผลเฉลย','การแก้สมการด้วยคอมพิวเตอร์ต้องตรวจทั้ง residual และความสมเหตุสมผลทางกายภาพ โดยเฉพาะระบบที่ ill-conditioned','Residual r = F − Ku ควรมีค่าน้อยเมื่อเทียบกับขนาดแรงที่ใช้ แต่ residual ต่ำเพียงอย่างเดียวไม่ได้ยืนยันว่าโมเดลถูกต้อง','หลังแก้สมการให้ตรวจ reaction, equilibrium, deformation shape และผลของการเปลี่ยน stiffness ทีละตัว','matrix']
]}
};
function deepSvg(type){const base='viewBox="0 0 660 235" role="img" style="width:100%;max-height:250px;background:#f6fafb;border:1px solid #dce7e9;border-radius:12px" xmlns="http://www.w3.org/2000/svg"';const common='<defs><marker id="ar" markerWidth="9" markerHeight="9" refX="7" refY="3" orient="auto"><path d="M0 0L7 3L0 6Z" fill="#b14b35"/></marker></defs>';const g={beam:'<path d="M80 150H575" stroke="#28566b" stroke-width="8"/><path d="M95 158l-22 32h44z M565 158l-22 32h44z" fill="#8bb3b9"/><path d="M325 45V135" stroke="#b14b35" stroke-width="3" marker-end="url(#ar)"/><text x="338" y="74" font-size="18">P ↓</text><text x="68" y="215">A (pin)</text><text x="525" y="215">B (roller)</text><text x="310" y="176">L/2</text>',spring:'<path d="M85 20V210 M570 20V210" stroke="#456679" stroke-width="9"/><path d="M85 70h80l13-20 25 40 25-40 25 40 25-20h292 M85 145h80l13-20 25 40 25-40 25 40 25-20h292" fill="none" stroke="#33869b" stroke-width="3"/><text x="205" y="43">k₁</text><text x="205" y="117">k₂</text><path d="M570 107h68" stroke="#b14b35" stroke-width="3" marker-end="url(#ar)"/><text x="600" y="94">P</text>',bar:'<path d="M85 25V205" stroke="#456679" stroke-width="9"/><rect x="92" y="85" width="400" height="62" fill="#8cb7bd" stroke="#28566b" stroke-width="2"/><path d="M492 116h135" stroke="#b14b35" stroke-width="3" marker-end="url(#ar)"/><text x="567" y="101">P</text><path d="M92 177h400 M92 168v18 M492 168v18" stroke="#456679" stroke-width="2"/><text x="288" y="200">L</text>',support:'<path d="M85 125h470" stroke="#28566b" stroke-width="7"/><path d="M85 134l-22 35h44z M555 134l-22 35h44z" fill="#8bb3b9"/><path d="M310 45v68" stroke="#b14b35" stroke-width="3" marker-end="url(#ar)"/><text x="323" y="61">F</text><text x="105" y="207">restrained DOF</text><text x="425" y="207">free DOF</text>',matrix:'<rect x="65" y="42" width="160" height="140" rx="8" fill="#e0eff1" stroke="#2b7180"/><text x="91" y="94" font-size="24">k₁₁  k₁₂</text><text x="91" y="136" font-size="24">k₂₁  k₂₂</text><text x="244" y="113" font-size="30">×</text><rect x="285" y="58" width="92" height="110" rx="8" fill="#e0eff1" stroke="#2b7180"/><text x="313" y="104" font-size="24">u₁</text><text x="313" y="143" font-size="24">u₂</text><text x="397" y="113" font-size="30">=</text><rect x="444" y="58" width="92" height="110" rx="8" fill="#e0eff1" stroke="#2b7180"/><text x="471" y="104" font-size="24">F₁</text><text x="471" y="143" font-size="24">F₂</text>'};return '<svg '+base+'>'+common+(g[type]||g.beam)+'</svg>'}
function deepChapter(id){const d=DEEP[id];if(!d)return null;return '<div class="eyebrow">EXPANDED CHAPTER · '+id+'</div><div class="hero"><h1>'+esc(d.name)+'</h1><p class="lead">บทเรียนฉบับขยาย: อ่านความหมายทางกายภาพ ศึกษาที่มาของสมการ ทำตัวอย่าง และตรวจความเข้าใจทีละหัวข้อ</p></div><div class="note">รูปเป็นแผนภาพ SVG ที่จัดทำใหม่เพื่อการสอน ไม่ใช่ภาพคัดลอกจากตำรา · เนื้อหาใช้สมมติฐานตามที่ระบุในแต่ละหัวข้อ</div><nav class="lesson-index">'+d.sections.map((x,i)=>'<a class="pill-link" href="#deep-'+i+'" data-deepjump="deep-'+i+'">'+(i+1)+'. '+esc(x[0])+'</a>').join('')+'<a class="pill-link" href="#deep-test" data-deepjump="deep-test">แบบฝึกหัด</a></nav>'+d.sections.map((x,i)=>'<section class="section" id="deep-'+i+'"><div class="tag">SECTION '+id+'.'+(i+1)+'</div><h2>'+esc(x[0])+'</h2>'+deepSvg(x[4])+'<h3>Physical Meaning</h3><p>'+esc(x[1])+'</p><h3>Theory & Derivation</h3><p>'+esc(x[2])+'</p><h3>Worked Example</h3><p>'+esc(x[3])+'</p><div class="section-toolbar"><span class="small muted">ภาพและตัวอย่างประกอบ '+(i+1)+'/4</span><button class="text-button" data-deepnext="'+(i+1<d.sections.length?'deep-'+(i+1):'deep-test')+'">ไปส่วนถัดไป ↓</button></div></section>').join('')+'<section class="section" id="deep-test"><h2>แบบฝึกหัดท้ายบท</h2><p>อธิบายสมมติฐานของสมการหลัก เขียน FBD หรือแผนภาพที่เกี่ยวข้อง และตรวจหน่วยของตัวอย่างด้วยตนเอง</p><p class="small muted">แบบฝึกหัดคำนวณฉบับขยายจะเพิ่มและตรวจทานแยกจากบทนำเดิม</p><button class="primary-button" data-deepgo="'+(nextId(id)||'home')+'">ดูบทถัดไป →</button></section>'}
const oldNavigate=navigate;navigate=function(id){if(DEEP[id]&&id!=='1.1'){current=id;document.getElementById('top-title').textContent='SE Academy / Chapter '+id;document.getElementById('page').innerHTML=deepChapter(id);document.querySelectorAll('[data-deepjump],[data-deepnext]').forEach(b=>b.onclick=e=>{e.preventDefault();document.getElementById(b.dataset.deepjump||b.dataset.deepnext)?.scrollIntoView({behavior:'smooth',block:'start'})});document.querySelectorAll('[data-deepgo]').forEach(b=>b.onclick=()=>navigate(b.dataset.deepgo));renderOutline(document.getElementById('search').value);closeMenu();window.scrollTo(0,0);history.replaceState(null,'','#'+id)}else{oldNavigate(id);if(id==='1.1'){const target=document.getElementById('page');target.insertAdjacentHTML('beforeend','<section class="section"><h2>ภาพและตัวอย่างเพิ่มเติม</h2>'+DEEP['1.1'].sections.map((x,i)=>'<h3>'+esc(x[0])+'</h3>'+deepSvg(x[4])+'<p>'+esc(x[1])+'</p><p>'+esc(x[3])+'</p>').join('')+'</section>')}}};
navigate((location.hash||'#home').slice(1));
